"""
documents.py — Document generation: PDF, DOCX, XLSX, PPTX

All files are saved in data/output/ and the path is returned
to the agent core, which passes it to the bot handler for Telegram delivery.
"""

from datetime import datetime
from pathlib import Path

from loguru import logger

_PROJECT_ROOT = Path(__file__).parent.parent.parent
OUTPUT_DIR = _PROJECT_ROOT / "data" / "output"


def _ensure_output_dir() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _output_path(filename: str) -> Path:
    _ensure_output_dir()
    return OUTPUT_DIR / filename


def _timestamped_name(prefix: str, ext: str, filename: str | None) -> str:
    if filename and filename.endswith(f".{ext}"):
        return filename
    if filename:
        return f"{filename}.{ext}"
    return f"{prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{ext}"


# ─── Utility ──────────────────────────────────────────────────────────────────

def _clean_text(text: str) -> str:
    """
    Replaces "fancy" Unicode characters (smart quotes, em-dashes) 
    with ASCII equivalents to prevent crashes in PDFs using standard fonts.
    """
    if not text:
        return ""
    replacements = {
        '\u2013': '-', # en-dash
        '\u2014': '-', # em-dash
        '\u2018': "'", # left single quote
        '\u2019': "'", # right single quote
        '\u201c': '"', # left double quote
        '\u201d': '"', # right double quote
        '\u2026': '...', # ellipsis
        '\u00a0': ' ',   # non-breaking space
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    
    # Final fallback: replaces any non-latin-1 character to avoid crashes
    return text.encode('latin-1', 'replace').decode('latin-1')


# ─── PDF ──────────────────────────────────────────────────────────────────────

def generate_pdf(title: str, content: str, filename: str | None = None) -> dict:
    """
    Generates a PDF document with a title and text content.
    """
    try:
        from fpdf import FPDF

        fname = _timestamped_name("document", "pdf", filename)
        out = _output_path(fname)

        # Clean text for standard font compatibility (Helvetica)
        clean_title = _clean_text(title)
        clean_content = _clean_text(content)

        pdf = FPDF()
        pdf.set_margins(20, 20, 20)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 18)
        pdf.multi_cell(0, 12, clean_title, align="C")
        pdf.ln(6)

        # Separator line
        pdf.set_draw_color(100, 100, 100)
        pdf.line(20, pdf.get_y(), 190, pdf.get_y())
        pdf.ln(6)

        # Body
        pdf.set_font("Helvetica", size=11)
        pdf.multi_cell(0, 7, clean_content)

        # Footer
        pdf.set_y(-15)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, f"Generated by Fraclaw - {datetime.now().strftime('%d/%m/%Y %H:%M')}", align="C")

        pdf.output(str(out))
        logger.info(f"📄 PDF generated: {out}")
        return {"success": True, "path": str(out), "filename": fname}

    except Exception as e:
        logger.error(f"Error generating PDF: {e}")
        return {"error": str(e)}


# ─── DOCX ─────────────────────────────────────────────────────────────────────

def generate_docx(title: str, content: str, filename: str | None = None) -> dict:
    """
    Generates a Word document (.docx) with title and content.

    Args:
        title:   Title (Heading 1).
        content: Body (double newlines become separate paragraphs).
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor

        fname = _timestamped_name("document", "docx", filename)
        out = _output_path(fname)

        doc = Document()

        # Clean text
        clean_title = _clean_text(title)
        clean_content = _clean_text(content)

        # Title
        heading = doc.add_heading(clean_title, level=0)
        heading.runs[0].font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)

        # Paragraphs (split by double newline)
        paragraphs = [p.strip() for p in clean_content.split("\n\n") if p.strip()]
        for para_text in paragraphs:
            p = doc.add_paragraph(para_text)
            p.style.font.size = Pt(11)

        # Footer
        doc.add_paragraph(
            f"\nGenerated by Fraclaw — {datetime.now().strftime('%d/%m/%Y %H:%M')}"
        ).runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

        doc.save(str(out))
        logger.info(f"📝 DOCX generated: {out}")
        return {"success": True, "path": str(out), "filename": fname}

    except Exception as e:
        logger.error(f"Error generating DOCX: {e}")
        return {"error": str(e)}


# ─── XLSX ─────────────────────────────────────────────────────────────────────

def generate_xlsx(
    title: str,
    data: list,
    headers: list | None = None,
    filename: str | None = None,
) -> dict:
    """
    Generates an Excel spreadsheet (.xlsx).

    Args:
        title:   Sheet title (used as tab name).
        data:    List of rows; each row is a list of values.
        headers: Column headers (optional, with blue background).
        filename: Output filename.

    Example:
        generate_xlsx(
            title="Expenses",
            headers=["Date", "Description", "Amount"],
            data=[["01/01/2025", "Rent", 800], ["05/01/2025", "Groceries", 120]]
        )
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill

        fname = _timestamped_name("spreadsheet", "xlsx", filename)
        out = _output_path(fname)

        wb = Workbook()
        ws = wb.active
        clean_title_sheet = _clean_text(title)[:31]
        ws.title = clean_title_sheet # Excel: max 31 characters for tab names

        # Header style
        header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True, size=11)
        header_align = Alignment(horizontal="center", vertical="center")

        start_row = 1
        if headers:
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=1, column=col_idx, value=header)
                cell.fill = header_fill
                cell.font = header_font
                cell.alignment = header_align
                ws.column_dimensions[cell.column_letter].width = max(15, len(str(header)) + 4)
            start_row = 2

        # Data
        for row_idx, row_data in enumerate(data, start_row):
            for col_idx, value in enumerate(row_data, 1):
                clean_value = _clean_text(str(value)) if isinstance(value, str) else value
                ws.cell(row=row_idx, column=col_idx, value=clean_value)

        wb.save(str(out))
        logger.info(f"📊 XLSX generated: {out}")
        return {"success": True, "path": str(out), "filename": fname}

    except Exception as e:
        logger.error(f"Error generating XLSX: {e}")
        return {"error": str(e)}


# ─── PPTX ─────────────────────────────────────────────────────────────────────

def generate_pptx(
    title: str,
    slides: list,
    filename: str | None = None,
) -> dict:
    """
    Generates a PowerPoint presentation (.pptx).

    Args:
        title:  Presentation title (opening slide).
        slides: List of dicts {"title": str, "content": str}.
        filename: Output filename.

    Example:
        generate_pptx(
            title="Project Presentation",
            slides=[
                {"title": "Introduction", "content": "Description..."},
                {"title": "Roadmap", "content": "Phase 1: ..."},
            ]
        )
    """
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.util import Pt

        fname = _timestamped_name("presentation", "pptx", filename)
        out = _output_path(fname)

        prs = Presentation()

        # ── Title Slide ──────────────────────────────────────
        title_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_layout)
        slide.shapes.title.text = _clean_text(title)
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = (
                f"Generated by Fraclaw - {datetime.now().strftime('%d/%m/%Y')}"
            )

        # ── Content Slides ───────────────────────────────────
        content_layout = prs.slide_layouts[1]
        for slide_data in slides:
            s = prs.slides.add_slide(content_layout)
            s.shapes.title.text = _clean_text(slide_data.get("title", ""))
            if len(s.placeholders) > 1:
                tf = s.placeholders[1].text_frame
                tf.text = _clean_text(slide_data.get("content", ""))
                for para in tf.paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(18)

        prs.save(str(out))
        logger.info(f"📊 PPTX generated: {out}")
        return {"success": True, "path": str(out), "filename": fname}

    except Exception as e:
        logger.error(f"Error generating PPTX: {e}")
        return {"error": str(e)}
